const pct=x=>typeof x==='number'?`${x.toFixed(1)}%`:'—';
const label={ai:'Indikasi tulisan AI',plagiarism:'Kemiripan sumber internet'};
const DB_NAME='ceknaskah-online-v1';
function db(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB_NAME,1);r.onupgradeneeded=()=>r.result.createObjectStore('reports',{keyPath:'id'});r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
export async function readReports(){const d=await db();return new Promise((resolve,reject)=>{const r=d.transaction('reports').objectStore('reports').getAll();r.onsuccess=()=>{d.close();resolve(r.result.sort((a,b)=>b.createdAt.localeCompare(a.createdAt)));};r.onerror=()=>{d.close();reject(r.error);};});}
export async function putReport(report){const existing=await readReports();const d=await db();return new Promise((resolve,reject)=>{const tx=d.transaction('reports','readwrite'),store=tx.objectStore('reports');store.put(report);for(const old of existing.slice(49))store.delete(old.id);tx.oncomplete=()=>{d.close();resolve();};tx.onerror=tx.onabort=()=>{d.close();reject(tx.error);};});}
const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function onlineReportHtml(r){
 const cards=Object.entries(r.results).map(([kind,x])=>`<section><h2>${escape(label[kind])}</h2><strong>${x.status==='complete'?pct(kind==='ai'?x.aiScore:x.score):'Tidak tersedia'}</strong><p>${escape(x.error||'')}</p><p>${x.creditsUsed??'—'} kredit digunakan</p></section>`).join('');
 const sources=(r.results.plagiarism?.sources||[]).map(s=>`<article><h3>${escape(s.title)}</h3>${s.url?`<a href="${escape(s.url)}" rel="noreferrer">${escape(s.url)}</a>`:''}<p>${pct(s.score)} kemiripan · ${s.matchedWords??'—'} kata cocok</p>${s.passages.map(p=>`<blockquote>${escape(p.text)}</blockquote>`).join('')}</article>`).join('');
 return `<!doctype html><html lang="id"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; base-uri 'none'; form-action 'none'"><title>Laporan CekNaskah Online</title><style>body{font:16px/1.7 system-ui;max-width:900px;margin:40px auto;padding:20px;color:#153c36}h1{font-size:30px}strong{font-size:24px}section,article{border-bottom:1px solid #ccc;padding:20px 0}a{overflow-wrap:anywhere}pre{white-space:pre-wrap;font:inherit}blockquote{margin-left:0;border-left:3px solid;padding-left:16px}@media print{body{margin:0}.print-note{display:none}}</style><h1>${escape(r.title)}</h1><p>CekNaskah Online · Winston AI · ${escape(r.createdAt)}</p><p class="print-note">Gunakan menu Cetak browser → Simpan sebagai PDF.</p><p>Skor AI adalah indikasi model, bukan persentase kata yang pasti dibuat AI. Kemiripan bukan keputusan plagiarisme. Hasil tidak menggunakan database atau sertifikasi Turnitin.</p>${cards}<h2>Rincian AI per kalimat</h2>${(r.results.ai?.sentences||[]).map(s=>`<p><b>${pct(s.aiScore)}</b> ${escape(s.text)}</p>`).join('')}<h2>Sumber pembanding</h2>${sources}<h2>Naskah yang diperiksa</h2><pre>${escape(r.text)}</pre></html>`;
}
